booksearch/urls.py
from django.urls import path

from . import views

app_name = 'booksearch'

urlpatterns = [
    path('', views.index, name='index'),
    path('book-result', views.book_result, name="book_result")
]

courses/urls.py
from django.urls import path

from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.savematkul, name='courses')
]

danans_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('posts/', include('post_page.urls')),
    path('courses/', include('courses.urls')),
    path('informations/', include('informations.urls')),
    path('booksearch/', include('booksearch.urls'))
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index')
]

informations/urls.py
from django.urls import path

from . import views

app_name = 'informations'

urlpatterns = [
    path('', views.index, name='index')
]

post_page/urls.py
from django.urls import path

from . import views

app_name = 'post_page'

urlpatterns = [
    path('', views.post_page, name='post_page')
]

booksearch/models.py
from django.db import models

# Create your models here.

courses/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

class Matkul(models.Model):
	nama = models.CharField('Nama Mata Kuliah', max_length=60)
	dosen = models.CharField('Dosen Pengajar Matkul', max_length=60)
	jumlah_sks = models.PositiveIntegerField('SKS Mata Kuliah', validators=[MinValueValidator(1), MaxValueValidator(10)])
	deskripsi = models.TextField(blank=True)
	smt_diambil = models.CharField('Semester Matkul Diambil', max_length=20)
	r_kelas = models.CharField('Ruang Kelas Matkul', max_length=20)

home/models.py
from django.db import models

# Create your models here.

informations/models.py
from django.db import models

# Create your models here.

login_page/models.py
from django.db import models

# Create your models here.

post_page/models.py
from django.db import models

# Create your models here.

courses/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import Matkul

class MatkulForm(forms.ModelForm) :
        class Meta :
                model = Matkul
                fields = ['nama', 'dosen', 'jumlah_sks', 'deskripsi',
                'smt_diambil', 'r_kelas']
        nama = forms.CharField(label='Nama Mata Kuliah', max_length=60) 
        dosen = forms.CharField(label='Dosen Pengajar Matkul', max_length=60) 
        jumlah_sks = forms.IntegerField(label='SKS Mata Kuliah', min_value=1, max_value=10 ) 
                # validators=[MinValueValidator(1), MaxValueValidator(10)]
        deskripsi = forms.CharField(label='Deskripsi Mata Kuliah') 
        smt_diambil = forms.CharField(label='Semester Matkul Diambil', max_length=20) 
        r_kelas = forms.CharField(label='Ruang Kelas Matkul', max_length=20)

booksearch/views.py
from django.shortcuts import render
from django.http import JsonResponse
import requests
import json

# Create your views here.

def index(request):
    context = {'page':'book_search'}
    return render(request, "booksearch.html", context)

def book_result(request):
    url = "https://www.googleapis.com/books/v1/volumes?q=" + request.GET["q"]
    data = requests.get(url)
    content = json.loads(data.content)
    return JsonResponse(content, safe=False)

courses/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .forms import MatkulForm

# Create your views here.

def savematkul(request):
    # if this is a POST request we need to process the form data
    form = MatkulForm(request.POST or None)

    if (form.is_valid and request.method == 'POST'):
        form.save()
        return redirect('courses:courses')
    else :
        return render(request, 'courses.html', {'page' : 'courses', 'matkul_form' : MatkulForm})

    #     # create a form instance and populate it with data from the request:
    #     form = MatkulForm(request.GET)
    #     # check whether it's valid:
    #     if form.is_valid():
    #         form.save()
    #         return HttpResponseRedirect('courses/')

    # # if a GET (or any other method) we'll create a blank form
    # else:
    #     form = NameForm()

    # return render(request, 'name.html', {'form': form})

home/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'index.html', {'page' : 'home'})

informations/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context = {
        'page' : 'informations'
    }
    return render(request, 'info-index.html', context)

login_page/views.py
from django.shortcuts import render

# Create your views here.

post_page/views.py
from django.shortcuts import render

# Create your views here.

def post_page(request):
    return render(request, 'post-page.html', {'page' : 'post_page'})

booksearch/templates/booksearch.html
{% extends "base.html" %}

{% load static %}

{% block css_block %} <link rel="stylesheet" href="{% static 'booksearch.css' %}"> {% endblock %}

{% block js_block %} <script src="{% static 'booksearch.js' %}"></script> {% endblock %}

{% block title %} Danan's BookSearch {% endblock %}



{% block content %} 
    <!-- <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12"> -->

    <h2 style="margin-top: 50px;text-align: center;">BookSearch</h2>

    <div class="section" style="margin-top: 10px;">
        <div class="searchBox-container">
            <input type="text" id="searchBox" placeholder="Cari buku..." name="keyword">
        </div>

        <div id="bookList">

        </div>

        <!-- <a href="${bookLink}">
            <button type="button" class="book-button">Lihat buku di Google Books</button>
        </a> -->
        <!-- <div class="bookView-container">
            <p>
                henlo <br>
                xixixi <br>
                heheh
            </p>
        </div> -->

        <!-- <div class="bookView-container">
            <div class="bookImg-container">
                <img src=${img_link} class="bookImg">
            </div>
            
            <div class="bookDesc">
                <h3 class="bookTitle">Sebuah Title</h3>
                <p>
                    <span class="bookDetails">Penulis:</span> Seorang Penulis <br>
                    <span class="bookDetails">Penerbit:</span> Sebuah Penerbit <br>
                    <span class="bookDetails">Tahun:</span> Sebuah Tahun <br>
                </p>
            </div>
        </div> -->
    </div>
{% endblock %}

  

courses/templates/courses.html
{% extends "base.html" %}

{% block title %} Danan's Courses {% endblock %}

{% load static %}

{% block content %} 
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-10">

                <!-- <form method="get">
                    {% csrf_token %}
                    <input type="text">
                    <button type="submit">Submit</button>
                </form> -->

                
                 
                
                
                <!-- <div style="float: left; margin-right: 20px;">
                    <label for="id_nama">Nama Mata Kuliah</label> <br>
                    <label for="id_dosen">Dosen Pengajar Matkul</label> <br>
                    <label for="id_jumlah_sks">SKS Mata Kuliah</label> <br>
                    <label for="id_deskripsi">Deskripsi Mata Kuliah</label> <br>
                    <label for="id_smt_diambil">Semester Matkul Diambil</label><br>
                    <label for="id_r_kelas">Ruang Kelas Matkul</label><br>
                </div>
                 -->
                
                <div>
                    <!-- <input type="text" name="nama" maxlength="60" required id="id_nama"><br>
                    <input type="text" name="dosen" maxlength="60" required id="id_dosen"><br>
                    <input type="number" name="jumlah_sks" required id="id_jumlah_sks"><br>
                    <input type="text" name="deskripsi" required id="id_deskripsi"><br>
                    <input type="text" name="smt_diambil" maxlength="20" required id="id_smt_diambil"><br>
                    <input type="text" name="r_kelas" maxlength="20" required id="id_r_kelas"><br> -->
                    <form action="savematkul">
                        {% csrf_token %}

                        {{ matkul_form.as_p }}
                        

                        <input type="submit" value="Submit">
                    </form>
                    

                </div>

            </div>
        </div>
    </div>
{% endblock %}

home/templates/index.html
{% extends "base.html" %}

{% block title %} Danan's Profile {% endblock %}

{% load static %}

{% block content %} 
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <span class="align-middle">
                    <div class="main-biodata">
                        <img src="{% static '1x1.jpg' %}" width=80px height=80px style="float: left; margin-right: 10px;"/>
                        <div id="name">Danan Maulidan Akbar</div>
                        <div id="major">1906293000 <br>
                        Ilmu Komputer UI 2019</div>
                    </div>
                </span>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <span class="section">
                    <h4 style="text-align: center; white-space: nowrap; padding-top: 10px;">Pendidikan</h4>

                    <img src="{% static 'asset2.png' %}" height=280px style="float: left; margin: 18px 10px; margin-bottom: 0px;">
                    <div class="education">
                        <span id="school">Universitas Indonesia <br></span>
                        <span id="detail">Ilmu Komputer 2019</span>
                    </div>
                    <div class="education">
                        <span id="school">SMAN 26 Jakarta <br></span>
                        <span id="detail">MIPA 2019</span>
                    </div>
                    <div class="education">
                        <span id="school">SMPN 182 Jakarta <br></span>
                        <span id="detail">182'33 2016</span>
                    </div>
                    <div class="education">
                        <span id="school">SDN Pengadegan 03 <br></span>
                        <span id="detail">2013</span>
                    </div>
                </span>
            </div>

            <div class="col-sm-8">
                <span class="section">
                    <h4 style="padding-left: 20px; padding-top: 10px;">Tentang Saya</h4>
                    <p>Nama saya Danan Maulidan Akbar, biasa dipanggil Danan. Saya adalah mahasiswa Ilmu Komputer UI.
                    Saya saat ini merupakan Staf Biro Media BEM Fasilkom UI 2020. Tidak begitu banyak pengalaman saya dalam desain, 
                    tetapi saya merupakan pribadi yang ingin belajar.
                    </p>
                </span>

                <span class="section">
                    <h4 style="padding-left: 20px; padding-top: 10px;">Hobi</h4>
                    <p>Saya menyukai linguistik. Logika linguistik merupakan bekal saya sebelum berkuliah di Fasilkom.
                        Bagaimana tidak, sintaksis kebahasaan dan pemrograman mirip. Hobi saya yang lainnya adalah <i>scroll</i>
                        Twitter :).
                    </p>
                </span>
            </div>
            <div class="col-xl-1">
                <span class="section">
                        <a href="https://www.instagram.com/danan_akbar/">
                            <img src="{% static 'logo_ig.png' %}" width="40" height="40" style="display: block; margin: auto;">
                        </a>
                        
                        <a href="https://twitter.com/dananmakbar">
                            <img src="{% static 'logo_twt.pn' %}g"width="50" height="50" style="display: block; margin: auto;">
                        </a>
                </span>
            </div>
        </div>
    </div>
{% endblock %}

  

home/templates/index_temp.html
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="media/style.css">
    <title>Danan's - Profile</title>
</head>
<body>
    <header class="container-fluid">
        <div class="topnav">
            <a class="active" href="#index">Profile</a>
            <a href="post-page.html">Posts</a>
          </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <span class="align-middle">
                    <div class="main-biodata">
                        <img src="media/1x1.jpg" width=80px height=80px style="float: left; margin-right: 10px;"/>
                        <div id="name">Danan Maulidan Akbar</div>
                        <div id="major">1906293000 <br>
                        Ilmu Komputer UI 2019</div>
                    </div>
                </span>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3">
                <span class="section">
                    <h4 style="text-align: center; white-space: nowrap; padding-top: 10px;">Pendidikan</h4>

                    <img src="media/asset2.png" height=280px style="float: left; margin: 18px 10px; margin-bottom: 0px;">
                    <div class="education">
                        <span id="school">Universitas Indonesia <br></span>
                        <span id="detail">Ilmu Komputer 2019</span>
                    </div>
                    <div class="education">
                        <span id="school">SMAN 26 Jakarta <br></span>
                        <span id="detail">MIPA 2019</span>
                    </div>
                    <div class="education">
                        <span id="school">SMPN 182 Jakarta <br></span>
                        <span id="detail">182'33 2016</span>
                    </div>
                    <div class="education">
                        <span id="school">SDN Pengadegan 03 <br></span>
                        <span id="detail">2013</span>
                    </div>
                </span>
            </div>

            <div class="col-sm-8">
                <span class="section">
                    <h4 style="padding-left: 20px; padding-top: 10px;">Tentang Saya</h4>
                    <p>Nama saya Danan Maulidan Akbar, biasa dipanggil Danan. Saya adalah mahasiswa Ilmu Komputer UI.
                    Saya saat ini merupakan Staf Biro Media BEM Fasilkom UI 2020. Tidak begitu banyak pengalaman saya dalam desain, 
                    tetapi saya merupakan pribadi yang ingin belajar.
                    </p>
                </span>

                <span class="section">
                    <h4 style="padding-left: 20px; padding-top: 10px;">Hobi</h4>
                    <p>Saya menyukai linguistik. Logika linguistik merupakan bekal saya sebelum berkuliah di Fasilkom.
                        Bagaimana tidak, sintaksis kebahasaan dan pemrograman mirip. Hobi saya yang lainnya adalah <i>scroll</i>
                        Twitter :).
                    </p>
                </span>
            </div>
            <div class="col-xl-1">
                <span class="section">
                        <a href="https://www.instagram.com/danan_akbar/">
                            <img src="media/logo_ig.png" width="40" height="40" style="display: block; margin: auto;">
                        </a>
                        
                        <a href="https://twitter.com/dananmakbar">
                            <img src="media/logo_twt.png"width="50" height="50" style="display: block; margin: auto;">
                        </a>
                </span>
            </div>
        </div>
    </div>

    <!-- <footer class="container-fluid">
        <div class="row center">
            <div class="col-lg-12">
                <span class="text-center">
                    Created by Danan
                </span>
            </div>
        </div>
    </footer> -->

</body>
</html>

informations/templates/info-index.html
{% extends "base.html" %}

{% load static %}

{% block css_block %} <link rel="stylesheet" href="{% static 'informations.css' %}"> {% endblock %}

{% block js_block %} <script src="{% static 'informations.js' %}"></script> {% endblock %}

{% block title %} Danan's Informations {% endblock %}



{% block content %} 
    <!-- <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12"> -->

    <h2 style="margin-top: 50px;text-align: center;">Informations</h2>

    <div class="section" style="margin-top: 10px;">
        <div class="acc-container" id="acc-cont1">
            <div class="accordion" id="acc1" onclick="openPanel('acc1', 'panel1')"> 
                Aktivitas Saat Ini
                <div class="acc-button-nav-container">
                    <img src="{% static 'ButtonUp.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accUp('acc-cont1')">
                    <img src="{% static 'ButtonDown.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accDown('acc-cont1')">                    
                </div>
            </div>
            <div class="acc-panel" id="panel1">
                <p>
                    Saat ini, saya sedang mengikuti PJJ Fasilkom UI yang disebabkan oleh pandemi COVID-19. Selain itu, saya 
                    juga mengikuti organisasi untuk pengembangan diri.
                </p> 
            </div>
        </div>

        <div class="acc-container" id="acc-cont2">
            <div class="accordion" id="acc2" onclick="openPanel('acc2', 'panel2')"> 
                Pengalaman Organisasi dan Kepanitiaan
                <div class="acc-button-nav-container">
                    <img src="{% static 'ButtonUp.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accUp('acc-cont2')">
                    <img src="{% static 'ButtonDown.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accDown('acc-cont2')">                    
                </div>
            </div>                

            <div class="acc-panel" id="panel2">
                <p>
                    Organisasi: <br>
                    Staf Biro Media BEM Fasilkom UI 2020
                    <br><br>

                    Kepanitiaan:
                    <ol class="panel-ol">
                        <li>Staf Perlengkapan PEMIRA Fasilkom UI 2019</li>
                        <li>Staf Kreatif Wisuda Genap Fasilkom UI 2019</li>
                        <li>Staf Mentor dan Peserta BETIS 2020</li>
                    </ol>
                </p> 
            </div>
        </div>

        <div class="acc-container" id="acc-cont3">
            <div class="accordion" id="acc3" onclick="openPanel('acc3', 'panel3')"> 
                Prestasi
                <div class="acc-button-nav-container">
                    <img src="{% static 'ButtonUp.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accUp('acc-cont3')">
                    <img src="{% static 'ButtonDown.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accDown('acc-cont3')">                    
                </div>
            </div>
            <div class="acc-panel" id="panel3">
                <p>
                    Saat ini, prestasi berupa kejuaraan yang saya dapatkan di masa kuliah ini belum ada. 
                    Namun, menurut saya, masuk ke dan bertahan di (kemudian lulus dari) Fasilkom 
                    merupakan prestasi (dan tujuan) paling besar bagi saya untuk saat ini. 
                </p> 
            </div>
        </div>

        <div class="acc-container" id="acc-cont4">
            <div class="accordion" id="acc4" onclick="openPanel('acc4', 'panel4')"> 
                Keterampilan Nonteknis
                <div class="acc-button-nav-container">
                    <img src="{% static 'ButtonUp.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accUp('acc-cont4')">
                    <img src="{% static 'ButtonDown.png'%}" class="acc-button-nav" 
                        onclick="event.stopPropagation(); accDown('acc-cont4')">                    
                </div>
            </div>
            <div class="acc-panel" id="panel4">
                <p>
                    Bahasa Asing:
                    <ol class="panel-ol">
                        <li>Bahasa Inggris</li>
                        <li>Bahasa Jerman</li>
                    </ol>
                </p>
                <p>
                    Perangkat Lunak:
                    <ol class="panel-ol">
                        <li>Adobe Illustrator</li>
                        <li>Adobe Photoshop</li>
                    </ol>

                </p> 
            </div>
        </div>
        
    </div>
{% endblock %}

  

post_page/templates/post-page.html
{% extends "base.html" %}

{% block title %} Danan's Posts {% endblock %}

{% load static %}

{% block content %}
<div class="container-fluid"> 
    <div class="row justify-content-center">
        <div class="col-10">
            <div class="section">
                <h4 style="padding-left: 20px; padding-top: 10px;">Jurusan di Fasilkom</h4>
                <img src="{% static 'makara-ui-fasilkom.png' %}" width="120px" style="display: block; margin: auto;">
                <p style="margin-top: 10px;">
                    Halo semua! Nama gue Danan. Di sini gue mau bahas tentang mata kuliah yang ada di Fasilkom UI. 
                    Di Fasilkom, kalian utamanya belajar tentang pemrograman, matematika, dan statistika. Namun, ada banyak 
                    lho jenis-jenis mata kuliah yang ada di Fasilkom. Mata kuliah ini ga selalu berhubungan dengan keduanya, lho.
                    Mata kuliah ini terbagi jadi 6 macam, yaitu:
                    <ol>
                        <strong><li>Wajib Universitas (UI)</li></strong>
                        Matkul wajib universitas ini adalah matkul penunjang dan sebagai pengantar setiap mata kuliah
                        pada setiap program studi yang ada di UI, khususnya untuk program S1. Matkulnya antara lain adalah
                        MPK (Mata Kuliah Pengembangan Kepribadian) Terintegrasi, MPK Olahraga/Seni, MPK Bahasa Inggris,
                        dan MPK Agama <br><br>

                        <strong><li>Wajib Rumpun (Sains dan Teknologi)</li></strong>
                        Matkul wajib rumpun adalah matkul yang menjadi landasan setiap prodi yang ada di rumpun tertentu.
                        Rumpun di UI untuk program S1 ada tiga, yaitu Ilmu Kesehatan (RIK), Sains dan Teknologi (Saintek),
                        serta Sosial dan Humaniora (Soshum). Prodi yang ada di rumpun Saintek adalah prodi yang ada di bawah
                        naungan FMIPA, FT, dan Fasilkom. Contoh matkulnya adalah Fisika Dasar dan Matematika Dasar 1 
                        (Kalkulus 1).<br><br>

                        <strong><li>Wajib Fakultas (Fasilkom)</li></strong>
                        <strong><li>Wajib Program Studi (Ilmu Komputer atau Sistem Informasi)</li></strong>
                        <strong><li>Peminatan</li></strong>
                        <strong><li>Eksternal</li></strong>
                    </ol>
                </p>

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'home/style.css' %}">    
    {% block css_block %} {% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <div class="topnav">
            <a class="{% if page == 'home' %}active{% endif %}" href="{% url 'home:index' %}">Profile</a>
            <a class="{% if page == 'post_page' %}active{% endif %}" href="{% url 'post_page:post_page' %}">Posts</a>
            <a class="{% if page == 'informations' %}active{% endif %}" href="{% url 'informations:index' %}">Informations</a>
            <a class="{% if page == 'book_search' %}active{% endif %}" href="{% url 'booksearch:index' %}">BookSearch</a>
          </div>
    </header>

    {% block content %}
    
    {% endblock %}

</body>

{% block js_block %} {% endblock %}

</html>